TOPIC_LIST = [
    "expanding and factorising",
    "solving linear equations",
    "solving quadratic equations",
    "sets and Venn diagrams",
    "angles",
    "exponents and surds",
    "simultaneous equations",
    "Pythagoras",
    "mensuration",
    "topics in arithmetic",
    "straight lines",
    "trigonometry",
    "similarity",
    "transformations",
    "vectors",
    "probability",
    "functions",
    "sequences",
    "circle theorems",
    "variation and proportion",
    "logarithms",
    "inequalities",
    'statistics',
]